name = "Survival"
build_directory = "exports"
love_version = "11.5"
icon_file = "assets/player.png"

love_files = [
    "+*",
    "-*/.*",
    "-./makelove-build/*",
]

default_targets = ["win32", "win64", "lovejs", "macos"]

[lovejs]
title = "game"